version: '3.5'

services:

  vod.mui:
    container_name: vod.mui
    build:
      context: .
      dockerfile: ./resources/docker/Dockerfile
    volumes:
      - '.:/usr/src/app'
      - './node_modules:/usr/src/app/node_modules'
    ports:
      - '8002:3000'
    environment:
      - NODE_ENV=development
      - NODE_PATH=src/