export const LAST_VIDEO_REQUEST_LOAD = 'LAST_VIDEO_REQUEST_LOAD';
export const LAST_VIDEO_REQUEST_SUCCESS = 'LAST_VIDEO_REQUEST_SUCCESS';
export const LAST_VIDEO_REQUEST_ERROR = 'LAST_VIDEO_REQUEST_ERROR';

export const VIDEO_DETAILS_REQUEST_LOAD = 'VIDEO_DETAILS_REQUEST_LOAD';
export const VIDEO_DETAILS_REQUEST_SUCCESS = 'VIDEO_DETAILS_REQUEST_SUCCESS';
export const VIDEO_DETAILS_REQUEST_ERROR = 'VIDEO_DETAILS_REQUEST_ERROR';
